### ISSUE TITLE
Java NEP11 tutorial not working

### ISSUE THREAD

**Issue by Lorenzobattistela** [neow3j/neow3j-boilerplate#9]
I'm not sure if this tutorial is made by the maintainers of the repo, but anyway.

https://developers.neo.org/tutorials/2023/10/17/neow3j-nep11

This recent tutorial teaches how to deploy a nep11 token with java. Well, I have gradle working and i simply copied the contract and tried to deploy. Compiling goes well, but the VM fails with exception on build / test / deploy.

The exception is:

```
> Task :test

NonFungibleToken > initializationError FAILED
    java.lang.Exception at ContractTestExtension.java:88
        Caused by: io.neow3j.transaction.exceptions.TransactionConfigurationException at TransactionBuilder.java:428

1 test completed, 1 failed

> Task :test FAILED

FAILURE: Build failed with an exception.
```

And investigating more I found:

`java.lang.Exception: io.neow3j.transaction.exceptions.TransactionConfigurationException: The vm exited due to the following exception: Object reference not set to an instance of an object.`

![image](https://github.com/neow3j/neow3j-boilerplate-contracts/assets/70359945/b82e2d34-9b15-4660-816a-6f5ac4304514)

Does anyone know how to solve this?

**Comment by mialbu** [comment]
Hey @Lorenzobattistela, I assume you haven't passed any data in the deployment. So, the vm tries to access a value that's not there.

To simplify the example, I've pushed a change in our NEP-11 example (see [here](https://github.com/neow3j/neow3j-examples-java/blob/dc5f20a235a4b30fcb331b3d1714a731ec2a86c8/src/main/java/io/neow3j/examples/contractdevelopment/contracts/NonFungibleToken.java)) that will not require this any longer. Please try deploying that updated example contract. If you want to use a different owner in that updated example, you'll have to set it in the contract directly.

**Comment by Lorenzobattistela** [comment]
![image](https://github.com/neow3j/neow3j-boilerplate-contracts/assets/70359945/6d3e94bb-3f14-47e0-b93f-7ba93963928f)

It's not compiling now, I'm investigating why (maybe is something in my environment)

**Comment by Lorenzobattistela** [comment]
Worked like a charm, thank you. Understood why it happened, idk how didnt I see it haha. Thanks!
